apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rd4lv4o2r-go 
  janus-idp.io/tekton: rd4lv4o2r-go
  backstage.io/kubernetes-id: rd4lv4o2r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rd4lv4o2r-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  